name: end-to-end test
runs:
  using: "composite"
  steps:
    - name: Check Python and iPython versions
      shell: bash
      run: pipenv run python --version && pipenv run ipython --version
    - name: install kernel
      shell: bash
      run: pipenv run ipython kernel install --name "python3" --user
    - name: run tests
      shell: bash
      run: pipenv run pytest -m "teste2e" tests/gui
